[[headers]]
for = "/*"
[headers.values]
cache-control = '''public,max-age=300,must-revalidate'''

[[headers]]
for = "/*.html"
[headers.values]
cache-control = '''public,max-age=300,must-revalidate'''

[[headers]]
for = "/*.*"
[headers.values]
cache-control = '''public,max-age=86400,must-revalidate'''

[[redirects]]
from = "/*"
to = "/dist/404.html"
status = 404
